provider"m3"{}
resource"m3_instance""my-server"{
image="Ubuntu18"
instance_name=var.vm_name
region_name=var.region
tenant_name=var.tenantName
shape="MEDIUM"
owner=var.owner
key_name=var.keyName
}
variable"vm_name"{
default="auto-test-tf-template-vmware"
description="NameforVMtobecreated"
}
variable"owner"{
default=""
description="NameforVMtobecreated"
}

variable"region"{
description="region"
}

variable"tenantName"{
description="tenantName"
}
variable"keyName"{
description="keyName"
}
