provider"m3"{}
resource"m3_instance""my-server"{
image="centos7_64-bit"
name=var.vm_name
region="EPAM-UA2"
tenant="EPM-CIT2"
shape="SMALL"
owner=var.owner
key=var.key
}

variable"vm_name"{
default="auto-test-tf-template-openstack"
description="NameforVMtobecreated"
}
variable"owner"{
default=""
description="NameforVMtobecreated"
}
variable"key"{
description="key"
}
